---
version: "2"

services:

  app:
    build: .
    environment:
      - MODE=dev
    volumes:
      - .:/code
    depends_on:
      - mongodb
    ports:
      - "9091:9090"

  mongodb:
    image: mongo:3.4.9
    restart: always
    environment:
        - TZ=America/New_York
    ports:
        - "27017:27017"
    logging:
        driver: json-file
        options:
            max-file: "10"
            max-size: "10m"

  mongo-client:
    image: mongoclient/mongoclient:2.2.0
    restart: always
    links:
        - mongodb
    volumes:
        - ./mongo-client-data:/data/db
    environment:
        - TZ=America/New_York
        - MONGO_URL=mongodb://mongodb:27017
    ports:
        - "3027:3000"
    logging:
        driver: json-file
        options:
            max-file: "10"
            max-size: "10m"