swagger: "2.0"

info:
  title: "Movements API"
  version: "1.0"

basePath: /v1

paths:

  /movements/{movement_id}:
    parameters:
      - $ref: '#/parameters/movement_id'
    put:
      parameters:
        - $ref: '#/parameters/movement_body'
      responses:
        '200':
          description: 'Get a movement by Id'
          schema:
            $ref: '#/definitions/Movement'


  /movements/:
    get:
      responses:
        '200':
          description: 'Fetch a list of movements'
          schema:
            type: array
            items:
              $ref: '#/definitions/Movement'
    post:
      parameters:
        - $ref: '#/parameters/movement_body'
      responses:
        '200':
          description: 'movement created'
          schema:
            $ref: '#/definitions/Movement'

parameters:
  movement_id:
    name: movement_id
    description: Movements's Unique identifier
    in: path
    type: integer
    required: true
  movement_body:
    in: body
    name: movement
    required: true
    schema:
      $ref: '#/definitions/Movement'

definitions:
  Movement:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        format: uuid