swagger: "2.0"

info:
  title: "Movements API"
  version: "1.0"

basePath: /v1

paths:

  /blocks:
    get:
      responses:
        '200':
          description: 'Fetch a list of blocks'
          schema:
            type: array
            items:
              $ref: '#/definitions/Block'

  /programs:
    get:
      responses:
        '200':
          description: 'Fetch a list of programs'
          schema:
            type: array
            items:
              $ref: '#/definitions/Program'

  /programs/{program_id}/generate_split:
    post:
      operationId: api.v1.programs.generate_split
      parameters:
        - name: program_id
          in: path
          description: ID of programs to use
          required: true
          type: string
          format: int64
        - name: config
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/SplitConfig'

      responses:
        '200':
          description: 'Fetch a list of programs'
          schema:
            type: array
            items:
              $ref: '#/definitions/SplitSession'

definitions:
  Block:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
        format: uuid

  Program:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
        format: uuid
  SplitSession:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
        format: uuid

  SplitConfig:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
        format: uuid